# Generated by Django 4.2.2 on 2023-06-15 22:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Activated'), ('D', 'Disabled')], default='A', max_length=100)),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('os_version', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100, unique=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('date_updated', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_equipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Activated'), ('D', 'Disabled')], default='A', max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'model_type',
            },
        ),
        migrations.CreateModel(
            name='PortEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Activated'), ('D', 'Disabled')], default='A', max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('observation', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ports', to='equipment.equipment')),
            ],
            options={
                'db_table': 'port_equipment',
            },
        ),
        migrations.CreateModel(
            name='ModelEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Activated'), ('D', 'Disabled')], default='A', max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_equipments', to='equipment.modeltype')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_equipments', to='vendor.vendor')),
            ],
            options={
                'db_table': 'model_equipment',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.modelequipment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_equipments', to=settings.AUTH_USER_MODEL),
        ),
    ]
